### ISSUE TITLE
About weight regularization

### ISSUE THREAD

**Issue by changshuowang** [CVMI-Lab/PAConv#4]
Hello author, thank you very much for providing such an excellent work. I have a question: Where can I find the weight regularization operation mentioned in the article? Or, in the process of code implementation, weight regularization is not used?

**Comment by mutianxu** [comment]
Hi @changshuowang ,

You can find the code of weight regularization (correlation loss) [here.](https://github.com/CVMI-Lab/PAConv/blob/main/scene_seg/tool/train.py#L200)

Please also note that, as mentioned in the paper, we do not add correlation_loss in both classification and part segmentation due to the simplicity of the tasks.

Regards,
Mutian

**Comment by changshuowang** [comment]
OK.&nbsp;Thank&nbsp;you&nbsp;brother.


---Original---
From: &quot;Mutian Xu ***@***.***&gt;
Date: Mon, May 10, 2021 20:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CVMI-Lab/PAConv] About weight regularization (#4)




 
Hi @changshuowang ,
 
You can find the code of weight regularization (correlation loss) here.
 
Please also note that, as mentioned in the paper, we do not add correlation_loss in both classification and part segmentation due to the simplicity of the tasks.
 
Regards,
 Mutian
 
&mdash;
